"""feed

Revision ID: b1cccc95f5ae
Revises: 8d8d5fd09bb4
Create Date: 2025-09-05 22:16:01.225094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1cccc95f5ae'
down_revision: Union[str, Sequence[str], None] = '8d8d5fd09bb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('PARK', 'MUSEUM', 'CAFE', 'RESTAURANT', 'BAR', 'GALLERY', 'THEATER', 'CINEMA', 'SHOP', 'SPORT', 'NATURE', 'HISTORIC', 'OTHER', name='placecategory'), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('loc_lat', sa.Float(), nullable=False),
    sa.Column('loc_lon', sa.Float(), nullable=False),
    sa.Column('opening_time', sa.Time(), nullable=True),
    sa.Column('closing_time', sa.Time(), nullable=True),
    sa.Column('working_days', sa.ARRAY(sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='weekday')), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('local_image_path', sa.String(length=300), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('price_level', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('places')
    # ### end Alembic commands ###
